### ISSUE TITLE
d2s init error : listToUpdate not defined

### ISSUE THREAD

**Issue by micheldumontier** [MaastrichtU-IDS/d2s-cli#10]
![image](https://user-images.githubusercontent.com/993852/78451940-c15dc800-7688-11ea-93e1-313651758111.png)

**Comment by vemonet** [comment]
Fixed: https://github.com/MaastrichtU-IDS/d2s-cli/commit/71bdc2a75df2f857bf722a6d302ef3aeea0daa50
